FROM apache/airflow:2.8.0-python3.11
USER root
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install psycopg2-binary requests
COPY main.py /opt/airflow/streaming/
